; generated by Component: ARM Compiler 5.06 update 7 (build 960) Tool: ArmCC [4d365d]
; commandline ArmCC [--c99 --split_sections --debug -c -S -ostm32c30dhal\main.s --depend=stm32c30dhal\main.d --cpu=Cortex-M4.fp.sp --apcs=interwork -O3 --diag_suppress=9931 -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I./SYSTEM/delay -I./SYSTEM/sys -I./SYSTEM/usart -I./HARDWARE -I./SYSTEM/mish -I./stm32c30dhal -I.\Balance -I.\RTE\_stm32c30dhal -IC:\Keil_v5\ARM\CMSIS\5.9.0\CMSIS\Core\Include -IC:\Keil_v5\Keil\STM32F4xx_DFP\2.9.0\Drivers\CMSIS\Device\ST\STM32F4xx\Include -D__UVISION_VERSION=537 -D_RTE_ -DSTM32F407xx -D_RTE_ -DUSE_HAL_DRIVER -DSTM32F407xx --omf_browse=stm32c30dhal\main.crf ../Core/Src/main.c]
        THUMB
        REQUIRE8
        PRESERVE8

        AREA ||i.Error_Handler||, CODE, READONLY, ALIGN=1

Error_Handler PROC
        CPSID    i
|L0.2|
        B        |L0.2|
        ENDP


        AREA ||i.HAL_Delay_us||, CODE, READONLY, ALIGN=2

HAL_Delay_us PROC
        PUSH     {r4,lr}
        MOV      r4,r0
        BL       HAL_RCC_GetHCLKFreq
        LDR      r1,|L1.44|
        UDIV     r0,r0,r1
        BL       HAL_SYSTICK_Config
        SUBS     r0,r4,#1
        BL       HAL_Delay
        BL       HAL_RCC_GetHCLKFreq
        MOV      r1,#0x3e8
        UDIV     r0,r0,r1
        POP      {r4,lr}
        B.W      HAL_SYSTICK_Config
        ENDP

|L1.44|
        DCD      0x000f4240

        AREA ||i.SystemClock_Config||, CODE, READONLY, ALIGN=2

SystemClock_Config PROC
        PUSH     {r4,r5,lr}
        SUB      sp,sp,#0x4c
        MOVS     r1,#0x30
        MOV      r0,sp
        BL       __aeabi_memclr4
        MOVS     r1,#0x14
        ADD      r0,sp,#0x30
        BL       __aeabi_memclr4
        LDR      r0,|L2.140|
        MOVS     r5,#0
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x10000000
        STR      r1,[r0,#0]
        LDR      r0,[r0,#0]
        AND      r0,r0,#0x10000000
        STR      r0,[sp,#0x44]
        LDR      r0,|L2.144|
        LDR      r1,[r0,#0]
        ORR      r1,r1,#0x4000
        STR      r1,[r0,#0]
        LDR      r0,[r0,#0]
        MOVS     r4,#2
        AND      r0,r0,#0x4000
        STR      r0,[sp,#0x44]
        MOVS     r0,#1
        STR      r0,[sp,#0xc]
        MOVS     r0,#0x10
        STR      r4,[sp,#0]
        STR      r4,[sp,#0x18]
        STR      r0,[sp,#0x10]
        STRD     r5,r0,[sp,#0x1c]
        MOV      r0,#0x150
        STRD     r0,r4,[sp,#0x24]
        MOVS     r0,#4
        STR      r0,[sp,#0x2c]
        MOV      r0,sp
        BL       HAL_RCC_OscConfig
        CBZ      r0,|L2.100|
        CPSID    i
|L2.98|
        B        |L2.98|
|L2.100|
        ADD      r1,sp,#0x30
        MOVS     r0,#0xf
        STM      r1,{r0,r4,r5}
        MOV      r0,#0x1400
        STR      r0,[sp,#0x3c]
        MOV      r0,#0x1000
        STR      r0,[sp,#0x40]
        MOVS     r1,#5
        ADD      r0,sp,#0x30
        BL       HAL_RCC_ClockConfig
        CMP      r0,#0
        BEQ      |L2.136|
        CPSID    i
|L2.134|
        B        |L2.134|
|L2.136|
        ADD      sp,sp,#0x4c
        POP      {r4,r5,pc}
        ENDP

|L2.140|
        DCD      0x40023840
|L2.144|
        DCD      0x40007000

        AREA ||i.main||, CODE, READONLY, ALIGN=2

main PROC
        BL       HAL_Init
        BL       SystemClock_Config
        BL       MX_GPIO_Init
        BL       MX_USART1_UART_Init
        BL       MX_ADC1_Init
        BL       MX_TIM1_Init
        BL       MX_TIM2_Init
        BL       MX_TIM3_Init
        BL       MX_TIM4_Init
        BL       MX_TIM5_Init
        BL       MX_TIM8_Init
        BL       MX_TIM9_Init
        BL       MX_TIM10_Init
        BL       MX_TIM11_Init
        BL       MX_UART5_Init
        BL       MX_USART2_UART_Init
        BL       MX_TIM12_Init
        BL       OLED_Init
        BL       delay_init
        BL       Robot_Select
        LDR      r1,|L3.132|
        MVN      r0,#1
        LDR      r1,[r1,#0]  ; htim12
        STR      r0,[r1,#0x10]
        LDR      r0,|L3.132|
        BL       HAL_TIM_Base_Start_IT
        LDR      r5,|L3.136|
        MOV      r4,#0x1000
        NOP      
|L3.104|
        BL       PS2_Read
        BL       show_task
        MOVS     r2,#1
        MOV      r1,r4
        MOV      r0,r5
        BL       HAL_GPIO_WritePin
        MOVS     r0,#5
        BL       Led_Flash
        B        |L3.104|
        ENDP

        DCW      0x0000
|L3.132|
        DCD      htim12
|L3.136|
        DCD      0x40020000

        AREA ||.arm_vfe_header||, DATA, READONLY, NOALLOC, ALIGN=2

        DCD      0x00000000

;*** Start embedded assembler ***

#line 1 "../Core/Src/main.c"
	AREA ||.rev16_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_main____REV16|
#line 463 "../Drivers/CMSIS/Include/cmsis_armcc.h"
|__asm___6_main_c_main____REV16| PROC
#line 464

 rev16 r0, r0
 bx lr
	ENDP
	AREA ||.revsh_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_main____REVSH|
#line 478
|__asm___6_main_c_main____REVSH| PROC
#line 479

 revsh r0, r0
 bx lr
	ENDP
	AREA ||.rrx_text||, CODE
	THUMB
	EXPORT |__asm___6_main_c_main____RRX|
#line 665
|__asm___6_main_c_main____RRX| PROC
#line 666

 rrx r0, r0
 bx lr
	ENDP

;*** End   embedded assembler ***

__ARM_use_no_argv EQU 0

        EXPORT __ARM_use_no_argv
        EXPORT Error_Handler [CODE]
        EXPORT HAL_Delay_us [CODE]
        EXPORT SystemClock_Config [CODE]
        EXPORT main [CODE]

        IMPORT ||Lib$$Request$$armlib|| [CODE,WEAK]
        IMPORT __aeabi_memclr4 [CODE]
        IMPORT HAL_RCC_OscConfig [CODE]
        IMPORT HAL_RCC_ClockConfig [CODE]
        IMPORT HAL_Init [CODE]
        IMPORT MX_GPIO_Init [CODE]
        IMPORT MX_USART1_UART_Init [CODE]
        IMPORT MX_ADC1_Init [CODE]
        IMPORT MX_TIM1_Init [CODE]
        IMPORT MX_TIM2_Init [CODE]
        IMPORT MX_TIM3_Init [CODE]
        IMPORT MX_TIM4_Init [CODE]
        IMPORT MX_TIM5_Init [CODE]
        IMPORT MX_TIM8_Init [CODE]
        IMPORT MX_TIM9_Init [CODE]
        IMPORT MX_TIM10_Init [CODE]
        IMPORT MX_TIM11_Init [CODE]
        IMPORT MX_UART5_Init [CODE]
        IMPORT MX_USART2_UART_Init [CODE]
        IMPORT MX_TIM12_Init [CODE]
        IMPORT OLED_Init [CODE]
        IMPORT delay_init [CODE]
        IMPORT Robot_Select [CODE]
        IMPORT HAL_TIM_Base_Start_IT [CODE]
        IMPORT PS2_Read [CODE]
        IMPORT show_task [CODE]
        IMPORT HAL_GPIO_WritePin [CODE]
        IMPORT Led_Flash [CODE]
        IMPORT htim12 [DATA]
        IMPORT HAL_RCC_GetHCLKFreq [CODE]
        IMPORT HAL_SYSTICK_Config [CODE]
        IMPORT HAL_Delay [CODE]

        ATTR FILESCOPE
        ATTR SETVALUE Tag_ABI_PCS_wchar_t,2
        ATTR SETVALUE Tag_ABI_enum_size,1
        ATTR SETVALUE Tag_ABI_optimization_goals,3
        ATTR SETSTRING Tag_conformance,"2.09"
        ATTR SETVALUE AV,18,1

        ASSERT {ENDIAN} = "little"
        ASSERT {INTER} = {TRUE}
        ASSERT {ROPI} = {FALSE}
        ASSERT {RWPI} = {FALSE}
        ASSERT {IEEE_FULL} = {FALSE}
        ASSERT {IEEE_PART} = {FALSE}
        ASSERT {IEEE_JAVA} = {FALSE}
        END
